### ISSUE TITLE
[Request]:  Support parallel HDF5 IO in LCLS ana environment

### ISSUE THREAD

**Issue by rajanplumley** [lcls-users/lcls-users#57]
### Topic Description

Topics:

The current LCLS analysis environments on S3DF (`ana-4.0.60-py3`) is not built with parallel HDF5 IO capability (https://docs.h5py.org/en/stable/mpi.html)

This used to be available on the old LCLS psana system.  Having this allows users to use their own multithreaded MPI code to simultaneous write to HDF5 files, which is extremely useful when running calculations over large LCLS datasets.

An example use case in the context of the LCLS workflow:

1.) LCLS experiment (such as an XPCS experiment) collects hundreds of thousands of images from an area detector and saved to XTC.
2.) The raw images are cropped, calibrated, and background subtracted by `smalldata` and saved to HDF5.
3.) Processing the data in a single thread would take too long:  so to analyze the data, the user writes an MPI python program that loads the HDF5 smalldata payload, divides the images amongst the ranks, and performs a series of operations that aggregate the dataset of images into a new dataset of processed results, which is saved to a single HDF5 file.

**Comment by fredericpoitevin** [comment]
@rajanplumley - after discussing with @valmar and Silke, the answer is that this capability was indeed removed from psana some time ago (3-5 years). The preferred approach now is to use hdf5 Virtual DataSet (which we should document how to use here).

However, per @valmar advice, you can install this in an environment by doing `conda install -c conda-forge h5py="*"=mpi_openmpi_*`. It can not be installed in the same environment as psana because psana depends on the `nompi` version of `h5py`.

**Comment by rajanplumley** [comment]
Thanks @fredericpoitevin !  I'll close this and look into HDF5 virtual dataset

**Comment by fredericpoitevin** [comment]
Happy to look into it together, @rajanplumley! Maybe this could help getting started? https://github.com/lcls-users/btx/blob/main/btx/processing/peak_finder.py#L478
